apiVersion: v1
kind: Service
metadata:
  name: servicea-service
spec:
  type: LoadBalancer
  selector:
    app: servicea
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    